services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_ROOT_PASSWORD=admin1234
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
    - ./mysql_db:/var/lib/mysql

  postgres: 
    image: postgres
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=facu
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5432:5432
    volumes:
      - ./postgres_db:/var/lib/postgresql/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
      - PMA_HOST=mysql
    ports:
      - 8080:80